nbs/models_esrnn__esrnn.ipynb, nixtlats/models/esrnn/esrnn.py
It was required to add one to the available timestamps (`availablets`) for the count to be inclusive. 
﻿
=> Fix inclusive counting esrnn

nbs/losses.pytorch.ipynb, neuralforecast/losses/pytorch.py
The patch of the pytorch losses to inherit the `nn.module` class broke the previous documentation, as the `__init__`'s documentation default was using the documentation inherited from `nn.module.__init__`.
Changed all losses to have their own `__init__` documentation.
=> fixed pytorch losses' init documentation

nbs/_quarto.yml
There was a typo in the hierarchicalforecast url.
=> [FIX] Add correct link to hierarchicalforecast

nbs/common.base_recurrent.ipynb, nbs/models.tcn.ipynb, neuralforecast/common/_base_recurrent.py
base_recurrent had incorrect reshaping in the "if self.loss.return_params" section, which would cause models to fail when using distribution loss with return_params=true. An example of the error can be seen below:
This pull request fixes the torch.concat error with a proper reshaping. Tested the fix with TCN.
=> Fix: Fixed torch.concat in base_recurrent return params

nbs/losses.pytorch.ipynb, neuralforecast/losses/pytorch.py
In the sCRPS definition, the denominator should be the sum of the absolute value of the ys, but there is currently not absolute value, so I added it.
=> Fix: Fixed sCRPS in losses.pytorch notebook

nbs/models.ipynb, neuralforecast/auto.py
When running AutoHINT as a model inside the NeuralForecast class and trying to call .predict(), we get the following error:
I updated the AutoHINT class with a one line change to set the test_size for the HINT class to avoid this error.
=> [FIX]: AutoHINT to update HINT test_size

nbs/sidebar.yml
This PR adds a tutorial on how to use statsforecast, mlforecast, and neuralforecast in the same pipeline.
=> [FEAT] Add stats, ml, neural forecasting methods tutorial

nbs/common.scalers.ipynb, neuralforecast/common/_scalers.py
Fix a bug where `minmax` and `minmax1` scalers return NaN if some values in the input tensor are masked.
=> [FIX] MinMax scalers NaN when masked

nbs/core.ipynb, neuralforecast/core.py
Change the default value of `use_init_models` to False to fine-tune as the default behavior.
Print warning when the previously fitted model is deleted.
=> [FIX] Change default of `use_init_models`

README.md
The simple example from the readme was broken due to a parameter name change.
=> renamed max_epochs to max_steps in demo

nbs/common.base_windows.ipynb, nbs/core.ipynb, neuralforecast/common/_base_windows.py
Fixed a bug in the computation of the validation loss for windows-based models when scaling and using point losses. The validation loss was comparing scaled predictions against real values in the original scale. This impacted both early stopping and model selection for auto models.
=> [FIX] Fixed bug in validation loss scale

nbs/examples/Predictive_Maintenance.ipynb
Fixes the issue reported in #732.
=> remove branch from pip install in predictive maintenance example

.circleci/config.yml, .github/workflows/ci.yaml, .github/workflows/no-response.yaml
* Adds a bot that checks for issues with the "awaiting response" label and closes them if we haven't heard from the author in 30 days.
* Adds the concurrency key to the github CI to cancel checks when another commit is pushed to the same branch.
* Updates the environment setup for the nbdev-tests job in circleci.
=> CI updates

.github/workflows/release-drafter.yml
Updates the release drafter to use a github action instead of an app (the app has been removed from this repository already).
=> add release drafter action

nbs/core.ipynb
The denominator for the minmax scaler in utilsforecast was wrong, which was fixed in https://github.com/Nixtla/utilsforecast/pull/16 and added to v0.0.7. However, using the right denominator seems to have increased a bit the relative difference between the predictions with and without exogenous features in a test. This increases the tolerance for that test.
=> increase relative tolerance for minmax test

nbs/common.scalers.ipynb
Splits the import cell in `nbs/common.scalers.ipynb` so that the test doesn't run when building the docs.
=> split import cell in common_scalers

.gitmodules
Uses https in the submodule url so that installs from github work.
=> use https in submodule

nbs/common.base_recurrent.ipynb, nbs/models.ipynb, neuralforecast/auto.py, neuralforecast/models/hint.py
Fixed `n_head` to `n_heads` parameter in AutoPatchTST default config.
=> [FIX] Default AutoPatchTST config

.github/workflows/build-docs.yaml, .github/workflows/deploy.yaml, .gitmodules, nbs/core.ipynb, nbs/mint.json, nbs/models.ipynb
Makes the documentation at https://nixtla.github.io/neuralforecast redirect to https://nixtla.mintlify.app/neuralforecast. Also replaces the submodule Nixtla/docs with a checkout.
Also fixes #818
=> redirect to mintlify docs

nbs/common.base_auto.ipynb, nbs/common.base_multivariate.ipynb, nbs/common.base_recurrent.ipynb, nbs/common.base_windows.ipynb, nbs/common.scalers.ipynb, nbs/core.ipynb, nbs/examples/Neuralforecast_Map.ipynb, nbs/losses.numpy.ipynb, nbs/losses.pytorch.ipynb, nbs/models.hint.ipynb, nbs/models.ipynb, nbs/models.nbeatsx.ipynb, nbs/models.nhits.ipynb, nbs/utils.ipynb, neuralforecast/auto.py, neuralforecast/common/_base_multivariate.py, neuralforecast/common/_base_recurrent.py, neuralforecast/common/_base_windows.py, neuralforecast/common/_scalers.py, neuralforecast/models/nhits.py
* Splits the cell with imports and code so that the code doesn't run when building the documentation.
* Removes the env variables set in the notebooks so that code like `CUDA_VISIBLE_DEVICES='' nbdev_test` allows running the tests on the CPU in a machine with a CUDA GPU.
* Removes the span tags from some of the sections.
* Removes break tags from the descriptions.
* Fixes an equation in the scalers notebook.
=> split import cells and remove env variables from notebooks

nbs/losses.numpy.ipynb, nbs/losses.pytorch.ipynb
Splits the module description of the losses so that the equations are rendered in a separate cell.
=> split losses description

LICENSE
this PR changes the license to apache-2. this change comes from users' feedback regarding neuralforecast usage in productive environments.
=> chore: update license to apache-2

nbs/models.lstm.ipynb, neuralforecast/models/lstm.py
Closes #910 
Documentation for `LSTM` mentioned `encoder_activation` argument, but it was not present in `__init__`. This PR removes this from the docstring.
=> removed documentation for missing argument

nbs/models.timemixer.ipynb, neuralforecast/models/timemixer.py
This fixes the attribute that does not exist when `channel_independence=1`.
=> hotfix: replace self.pred_len with self.h

nbs/core.ipynb, neuralforecast/core.py
Fixes #1166:
Adds RMoK and AutoRMoK in model dict of core.ipynb
=> [FIX] Missing autormok in core.ipynb

.github/workflows/build-docs.yaml
To prevent many more issues like #1182, only build docs on release, not on push to main.
=> [FIX] Build docs on release only

nbs/models.nbeatsx.ipynb, neuralforecast/models/nbeatsx.py
Currently, using static variables only and specifying an 'exogenous' stack causes an error with NBEATSx.
```python
from neuralforecast.utils import AirPassengersDF, AirPassengersPanel, AirPassengersStatic
from neuralforecast.models import NBEATSx
Y_train_df = AirPassengersPanel[AirPassengersPanel.ds<AirPassengersPanel['ds'].values[-12]]
Y_test_df = AirPassengersPanel[AirPassengersPanel.ds>=AirPassengersPanel['ds'].values[-12]].reset_index(drop=True)
model = NBEATSx(h=12, input_size=24,
scaler_type='robust',
dropout_prob_theta=0.5,
stat_exog_list=['airline1'],
stack_types = ["identity", "trend", "seasonality", "exogenous"],
n_blocks = [1,1,1,1],
max_steps=200,
val_check_steps=10,
early_stop_patience_steps=2)
nf = NeuralForecast(
models=[model],
freq='ME'
)
nf.fit(df=Y_train_df, …
```
=> FIX: Allow static vars only with NBEATSx and exogenous block
