CONTRIBUTING.md, README.md, docs/index.html, nbs/index.ipynb
- remove authors section from readme
- improve contributing file and add it to readme
=> Improve contributing file

.github/workflows/ci-linux.yml, .github/workflows/ci-mac.yml, .github/workflows/coverage.yml
=> Decouple ci jobs

LICENSE, Makefile
- fix: correct library name Makefile and add conda_release instruction
- fix: update authors
=> Fix settings: Makefile and LICENSE

README.md, docs/index.html, nbs/index.ipynb
- fix: add new ci badges to readme
- fix: remove legacy name from readme
- feat: add website badge
=> Adjust README

LICENSE, README.md, docs/index.html, nbs/index.ipynb, settings.ini
- fix: update license file to GPL-3
- fix: update library license to GPLv3
=> Add GPLv3 License

docs/models_nbeats__nbeats.html, nbs/models_nbeats__nbeats.ipynb, nbs/models_nhits__nhits.ipynb, neuralforecast/models/nbeats/nbeats.py, neuralforecast/models/nhits/nhits.py
- fix: import pandas used by forecast method
- feat: set default values for X_df, S_df forecast method
=> Fix forecast method

docs/models_components__common.html
=> fix typo in models_components__common.html

nbs/data__tsdataset.ipynb, neuralforecast/data/tsdataset.py
=> fix: order of uid, ds cols

action_files/environment.yml, environment.yml
=> Fix nbdev version

nbs/losses__numpy.ipynb, nbs/losses__pytorch.ipynb, neuralforecast/losses/numpy.py, neuralforecast/losses/pytorch.py
=> fix: numpy smape

nbs/data_datasets__long_horizon.ipynb, neuralforecast/data/datasets/long_horizon.py
=> [FEAT] Add metadata for long horizon datasets

nbs/common.base_recurrent.ipynb, nbs/common.base_windows.ipynb, nbs/models.tft.ipynb, neuralforecast/common/_base_recurrent.py, neuralforecast/common/_base_windows.py, neuralforecast/models/tft.py
fixed return_params in predict_step of base_recurrent and base_windows
added return_params in predict_step of tft
=> return_params fixes

nbs/models.ipynb
This PR fixes the errors [raised by the docs deployment action](https://github.com/Nixtla/neuralforecast/actions/runs/4130061584/jobs/7136358161).
=> [FIX] Docs deployment

environment.yml, nbs/core.ipynb, neuralforecast/core.py, settings.ini
This PR allows installing `pandas>=1.3.5` (including the new `2.0.0` version). No core changes were required, just a minor change in a test.
=> [FEAT] Allow pandas 2

nbs/models.lstm.ipynb, nbs/models.mlp.ipynb, nbs/models.nhits_treat.ipynb, nbs/models.rnn.ipynb, nbs/models.tcn.ipynb, nbs/models.tft.ipynb, neuralforecast/common/_modules.py
-Sum total approach added to /neuralforecast/common/_modules.py 
-notebooks updated to take new treatment types: "log_normal" or "sum_total"
=> sum_total approach added

neuralforecast/auto.py, neuralforecast/common/_base_recurrent.py, neuralforecast/core.py, neuralforecast/models/lstm.py, neuralforecast/models/rnn.py, neuralforecast/models/tcn.py
Updated the concentrator branch with the 'inference_input_size' fix #536 in MAIN.
=> base recurrent fix - treat

nbs/examples/Robust_Regression.ipynb, nbs/models.nbeatsx.ipynb, neuralforecast/models/nbeatsx.py
Added dropout to NBEATSx.
Since individual models benefit from dropout regularization, this is the most common use case.
=> [Feat] NBEATSx dropout

nbs/common.base_windows.ipynb, neuralforecast/common/_base_windows.py
Issue will occur when using loss=DistributionLoss(distribution='Poisson') on a GPU machine. The reason is that the variables are not on the same device.
=> y_loc and y_scale should be on the same device as y_hat

nbs/examples/HierarchicalNetworks.ipynb
Added HINT paper reference in hierarchical forecast tutorial
=> [DOC] Added HINT paper reference in hierarchical forecast tutorial

.circleci/config.yml, action_files/test_models/requirements.txt, action_files/test_models/src/data.py, action_files/test_models/src/evaluation.py, action_files/test_models/src/evaluation2.py, action_files/test_models/src/models.py, action_files/test_models/src/models2.py, action_files/test_models/src/test.py
Improved tests of model performance in CI:
* Fixed bug on importing pandas caused by wrong paths.
* Split test in two files to shorten total time.
* Changes M3 Other to M3 Monthly.
* Improved configs
* Print model in for loop
* Change MAPE to MAE
* Change ETS for AutoARIMA baseline
=> [FIX] CI test-model-performance

nbs/common.base_recurrent.ipynb, neuralforecast/common/_base_recurrent.py
Fixes https://github.com/Nixtla/neuralforecast/issues/752
=> fix off by one error in BaseRecurrent available_ts

.github/workflows/lint.yaml, .mypy.ini, CONTRIBUTING.md, pyproject.toml, settings.ini
=> switch `flake8` to `ruff`

.all-contributorsrc, README.md
=> [FEAT] Model table in README

CONTRIBUTING.md
=> remove extra character from CONTRIBUTING.md

nbs/models.patchtst.ipynb
=> [FIX] fix_wrong_import_doc PatchTST

nbs/examples/Large_Datasets_Tutorial.ipynb, nbs/mint.json, nbs/sidebar.yml
A follow up tutorial for this review https://github.com/Nixtla/neuralforecast/pull/1049
=> [DOCS] add tutorial for large dataset DataLoader

nbs/core.ipynb, neuralforecast/core.py
Closes #1079 - more context in the linked issue
=> [FIX] ignore pytorch lightning's PossibleUserWarning

README.md
=> [DOCS] Add citation note

nbs/common.base_model.ipynb, nbs/common.base_multivariate.ipynb, nbs/common.base_recurrent.ipynb, nbs/common.base_windows.ipynb, neuralforecast/common/_base_model.py, neuralforecast/common/_base_multivariate.py, neuralforecast/common/_base_recurrent.py, neuralforecast/common/_base_windows.py
Fix for #1259. The example in #1259 fails without the fix, and succeeds with the fix.
=> [FIX] Adds bfloat16 support

neuralforecast/models/bitcn.py
One-line change as titled.
Related: #961
=> Update BiTCN doc dropout to match code
